# Generated by Django 4.0.5 on 2022-06-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_author', models.CharField(max_length=200)),
                ('last_name_author', models.CharField(max_length=200)),
                ('address_author', models.CharField(max_length=150)),
                ('amount_book', models.IntegerField(max_length=15)),
                ('email_author', models.EmailField(max_length=200)),
                ('date_release', models.DateField()),
            ],
        ),
    ]
